[package]
name = "risc0-compile-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
quote = "1.0"
dunce = "1.0.4"
toml = "0.8"
risc0-zkvm = "1.0.0-rc.5"
